export enum Events {
    ENTER_AIRSPACE  = "ENTER_AIRSPACE",
    LEAVE_AIRSPACE  = "LEAVE_AIRSPACE",
    PLANE_LAND      = "PLANE_LAND",
    PLANE_TAKEOFF   = "PLANE_TAKEOFF",
    PLANE_EMERGENCY = "PLANE_EMERGENCY",
}